from django.core.exceptions import ValidationError as ValidationError_

ValidationError = ValidationError_